sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_c5440c031ed9_key -iv $encrypted_c5440c031ed9_iv -in multi-k8s-304011-a84cce978f23.json.enc -out multi-k8s-304011-a84cce978f23.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $home/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-304011-a84cce978f23.json
  - 