sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f289f9698a7_key -iv $encrypted_9f289f9698a7_iv -in multi-k8s-304011-1ba8ca6465fd.json.enc -out multi-k8s-304011-1ba8ca6465fd.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-304011-1ba8ca6465fd.json
  - gcloud config set project multi-k8s-304011
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USRNAME" --password-stdin
  - docker build -t perugoal1/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true perugoal1/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on: 
    branch: master